### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by haigegithub** [yupd/es7-head-plugin#1]
{"error":"Incorrect HTTP method for uri [/_plugin/head/] and method [GET], allowed: [POST]","status":405}

**Comment by yupd** [comment]
> {"error":"Incorrect HTTP method for uri [/_plugin/head/] and method [GET], allowed: [POST]","status":405}

你使用的es7版本号是多少？
dist/plugin-descriptor.properties  需要改这个配置文件中es7的版本号和你用的版本号对应上。

**Comment by haigegithub** [comment]
我的es版本为7.3.1 dist/plugin-descriptor.properties为elasticsearch.version=7.3.1

**Comment by haigegithub** [comment]
grep -v ^# plugin-descriptor.properties |tr -s '\n'
description=A plugin for the head functionality
version=7.3.1
name=head
classname=org.elasticsearch.plugin.head.HeadPlugin
java.version=1.8
elasticsearch.version=7.3.1
has.native.controller=false

../../plugins/../bin/elasticsearch-plugin list
head

**Comment by yupd** [comment]
> grep -v ^# plugin-descriptor.properties |tr -s '\n' description=A plugin for the head functionality version=7.3.1 name=head classname=org.elasticsearch.plugin.head.HeadPlugin java.version=1.8 elasticsearch.version=7.3.1 has.native.controller=false
> 
> ../../plugins/../bin/elasticsearch-plugin list head

[head-7.3.1.zip](https://github.com/user-attachments/files/17339831/head-7.3.1.zip)
![20241011162239](https://github.com/user-attachments/assets/e4681bf6-edd5-4163-88d9-9c79809048e8)

需要改一下源码。
